apiVersion: v1
kind: Pod
metadata:
  name: "hello-test-connection"
  labels:
    app.kubernetes.io/name: hello
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['hello:80']
  restartPolicy: Never
